version: '3.3'

services:
  reverse-proxy-nginx:
    container_name: 'reverse-proxy-nginx'
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./site:/usr/share/nginx/html
      - ./dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/letsencrypt/etc/letsencrypt/live/kiwigaming.de/fullchain.pem:/etc/letsencrypt/live/kiwigaming.de/fullchain.pem
      - /docker-volumes/letsencrypt/etc/letsencrypt/live/kiwigaming.de/privkey.pem:/etc/letsencrypt/live/kiwigaming.de/privkey.pem
      - /docker-volumes/reverse-proxy/log/nginx:/var/log/nginx/log
    networks:
      - default

networks:
  default:
    driver: bridge
