version: '3.3'

services:
  minecraft-faul:
    container_name: 'minecraft-faul'
    image: itzg/minecraft-server:latest
    volumes:
      - /docker-volumes/minecraft-faul:/data
    ports:
      - "25565:25565"
    networks:
      - docker-network
    environment:
      - EULA=TRUE
      - CONSOLE=false
      - TYPE=SPIGOT
    restart: always

networks:
  docker-network:
    driver: bridge